permissions:
  id-token: write # Needed to federate tokens.

on:
  workflow_dispatch: {}
  
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: octo-sts/action@f603d3be9d8dd9871a265776e625a27b00effe05
      id: octo-sts
      with:
        scope: christophe-ak/sample-repo-test
        identity: write-issues
    - env:
        GITHUB_TOKEN: ${{ steps.octo-sts.outputs.token }}
      run: |
        gh issue create --title "It works" --body "Even works really well"
